<?php	
	/* 
	
		Timonix Arads
		system zarządzania serwisami timonix.pl
		di_Timonix
		
		zarządza strefą  czasową serwera
	
	*/
	
$languages_list = array(
    array("name" => "Afrikaans", "code" => "af", "native_name" => "Afrikaans", "id" => "1"),
    array("name" => "Albanian - shqip", "code" => "sq", "native_name" => "shqip", "id" => "2"),
    array("name" => "Amharic - አማርኛ", "code" => "am", "native_name" => "አማርኛ", "id" => "3"),
    array("name" => "Arabic - العربية", "code" => "ar", "native_name" => "العربية", "id" => "4"),
    array("name" => "Aragonese - aragonés", "code" => "an", "native_name" => "aragonés", "id" => "5"),
    array("name" => "Armenian - հայերեն", "code" => "hy", "native_name" => "հայերեն", "id" => "6"),
    array("name" => "Asturian - asturianu", "code" => "ast", "native_name" => "asturianu", "id" => "7"),
    array("name" => "Azerbaijani - azərbaycan dili", "code" => "az", "native_name" => "azərbaycan dili", "id" => "8"),
    array("name" => "Basque - euskara", "code" => "eu", "native_name" => "euskara", "id" => "9"),
    array("name" => "Belarusian - беларуская", "code" => "be", "native_name" => "беларуская", "id" => "10"),
    array("name" => "Bengali - বাংলা", "code" => "bn", "native_name" => "বাংলা", "id" => "11"),
    array("name" => "Bosnian - bosanski", "code" => "bs", "native_name" => "bosanski", "id" => "12"),
    array("name" => "Breton - brezhoneg", "code" => "br", "native_name" => "brezhoneg", "id" => "13"),
    array("name" => "Bulgarian - български", "code" => "bg", "native_name" => "български", "id" => "14"),
    array("name" => "Catalan - català", "code" => "ca", "native_name" => "català", "id" => "15"),
    array("name" => "Central Kurdish - کوردی (دەستنوسی عەرەبی)", "code" => "ckb", "native_name" => "کوردی (دەستنوسی عەرەبی)", "id" => "16"),
    array("name" => "Chinese - 中文", "code" => "zh", "native_name" => "中文", "id" => "17"),
    array("name" => "Chinese (Hong Kong) - 中文（香港）", "code" => "zh-HK", "native_name" => "中文（香港）", "id" => "18"),
    array("name" => "Chinese (Simplified) - 中文（简体）", "code" => "zh-CN", "native_name" => "中文（简体）", "id" => "19"),
    array("name" => "Chinese (Traditional) - 中文（繁體）", "code" => "zh-TW", "native_name" => "中文（繁體）", "id" => "20"),
    array("name" => "Corsican", "code" => "co", "native_name" => "Corsican", "id" => "21"),
    array("name" => "Croatian - hrvatski", "code" => "hr", "native_name" => "hrvatski", "id" => "22"),
    array("name" => "Czech - čeština", "code" => "cs", "native_name" => "čeština", "id" => "23"),
    array("name" => "Danish - dansk", "code" => "da", "native_name" => "dansk", "id" => "24"),
    array("name" => "Dutch - Nederlands", "code" => "nl", "native_name" => "Nederlands", "id" => "25"),
    array("name" => "English", "code" => "en", "native_name" => "English", "id" => "26"),
    array("name" => "English (Australia)", "code" => "en-AU", "native_name" => "English (Australia)", "id" => "27"),
    array("name" => "English (Canada)", "code" => "en-CA", "native_name" => "English (Canada)", "id" => "28"),
    array("name" => "English (India)", "code" => "en-IN", "native_name" => "English (India)", "id" => "29"),
    array("name" => "English (New Zealand)", "code" => "en-NZ", "native_name" => "English (New Zealand)", "id" => "30"),
    array("name" => "English (South Africa)", "code" => "en-ZA", "native_name" => "English (South Africa)", "id" => "31"),
    array("name" => "English (United Kingdom)", "code" => "en-GB", "native_name" => "English (United Kingdom)", "id" => "32"),
    array("name" => "English (United States)", "code" => "en-US", "native_name" => "English (United States)", "id" => "33"),
    array("name" => "Esperanto - esperanto", "code" => "eo", "native_name" => "esperanto", "id" => "34"),
    array("name" => "Estonian - eesti", "code" => "et", "native_name" => "eesti", "id" => "35"),
    array("name" => "Faroese - føroyskt", "code" => "fo", "native_name" => "føroyskt", "id" => "36"),
    array("name" => "Filipino", "code" => "fil", "native_name" => "Filipino", "id" => "37"),
    array("name" => "Finnish - suomi", "code" => "fi", "native_name" => "suomi", "id" => "38"),
    array("name" => "French - français", "code" => "fr", "native_name" => "français", "id" => "39"),
    array("name" => "French (Canada) - français (Canada)", "code" => "fr-CA", "native_name" => "français (Canada)", "id" => "40"),
    array("name" => "French (France) - français (France)", "code" => "fr-FR", "native_name" => "français (France)", "id" => "41"),
    array("name" => "French (Switzerland) - français (Suisse)", "code" => "fr-CH", "native_name" => "français (Suisse)", "id" => "42"),
    array("name" => "Galician - galego", "code" => "gl", "native_name" => "galego", "id" => "43"),
    array("name" => "Georgian - ქართული", "code" => "ka", "native_name" => "ქართული", "id" => "44"),
    array("name" => "German - Deutsch", "code" => "de", "native_name" => "Deutsch", "id" => "45"),
    array("name" => "German (Austria) - Deutsch (Österreich)", "code" => "de-AT", "native_name" => "Deutsch (Österreich)", "id" => "46"),
    array("name" => "German (Germany) - Deutsch (Deutschland)", "code" => "de-DE", "native_name" => "Deutsch (Deutschland)", "id" => "47"),
    array("name" => "German (Liechtenstein) - Deutsch (Liechtenstein)", "code" => "de-LI", "native_name" => "Deutsch (Liechtenstein)", "id" => "48"),
    array("name" => "German (Switzerland) - Deutsch (Schweiz)", "code" => "de-CH", "native_name" => "Deutsch (Schweiz)", "id" => "49"),
    array("name" => "Greek - Ελληνικά", "code" => "el", "native_name" => "Ελληνικά", "id" => "50"),
    array("name" => "Guarani", "code" => "gn", "native_name" => "Guarani", "id" => "51"),
    array("name" => "Gujarati - ગુજરાતી", "code" => "gu", "native_name" => "ગુજરાતી", "id" => "52"),
    array("name" => "Hausa", "code" => "ha", "native_name" => "Hausa", "id" => "53"),
    array("name" => "Hawaiian - ʻŌlelo Hawaiʻi", "code" => "haw", "native_name" => "ʻŌlelo Hawaiʻi", "id" => "54"),
    array("name" => "Hebrew - עברית", "code" => "he", "native_name" => "עברית", "id" => "55"),
    array("name" => "Hindi - हिन्दी", "code" => "hi", "native_name" => "हिन्दी", "id" => "56"),
    array("name" => "Hungarian - magyar", "code" => "hu", "native_name" => "magyar", "id" => "57"),
    array("name" => "Icelandic - íslenska", "code" => "is", "native_name" => "íslenska", "id" => "58"),
    array("name" => "Indonesian - Indonesia", "code" => "id", "native_name" => "Indonesia", "id" => "59"),
    array("name" => "Interlingua", "code" => "ia", "native_name" => "Interlingua", "id" => "60"),
    array("name" => "Irish - Gaeilge", "code" => "ga", "native_name" => "Gaeilge", "id" => "61"),
    array("name" => "Italian - italiano", "code" => "it", "native_name" => "italiano", "id" => "62"),
    array("name" => "Italian (Italy) - italiano (Italia)", "code" => "it-IT", "native_name" => "italiano (Italia)", "id" => "63"),
    array("name" => "Italian (Switzerland) - italiano (Svizzera)", "code" => "it-CH", "native_name" => "italiano (Svizzera)", "id" => "64"),
    array("name" => "Japanese - 日本語", "code" => "ja", "native_name" => "日本語", "id" => "65"),
    array("name" => "Kannada - ಕನ್ನಡ", "code" => "kn", "native_name" => "ಕನ್ನಡ", "id" => "66"),
    array("name" => "Kazakh - қазақ тілі", "code" => "kk", "native_name" => "қазақ тілі", "id" => "67"),
    array("name" => "Khmer - ខ្មែរ", "code" => "km", "native_name" => "ខ្មែរ", "id" => "68"),
    array("name" => "Korean - 한국어", "code" => "ko", "native_name" => "한국어", "id" => "69"),
    array("name" => "Kurdish - Kurdî", "code" => "ku", "native_name" => "Kurdî", "id" => "70"),
    array("name" => "Kyrgyz - кыргызча", "code" => "ky", "native_name" => "кыргызча", "id" => "71"),
    array("name" => "Lao - ລາວ", "code" => "lo", "native_name" => "ລາວ", "id" => "72"),
    array("name" => "Latin", "code" => "la", "native_name" => "Latin", "id" => "73"),
    array("name" => "Latvian - latviešu", "code" => "lv", "native_name" => "latviešu", "id" => "74"),
    array("name" => "Lingala - lingála", "code" => "ln", "native_name" => "lingála", "id" => "75"),
    array("name" => "Lithuanian - lietuvių", "code" => "lt", "native_name" => "lietuvių", "id" => "76"),
    array("name" => "Macedonian - македонски", "code" => "mk", "native_name" => "македонски", "id" => "77"),
    array("name" => "Malay - Bahasa Melayu", "code" => "ms", "native_name" => "Bahasa Melayu", "id" => "78"),
    array("name" => "Malayalam - മലയാളം", "code" => "ml", "native_name" => "മലയാളം", "id" => "79"),
    array("name" => "Maltese - Malti", "code" => "mt", "native_name" => "Malti", "id" => "80"),
    array("name" => "Marathi - मराठी", "code" => "mr", "native_name" => "मराठी", "id" => "81"),
    array("name" => "Mongolian - монгол", "code" => "mn", "native_name" => "монгол", "id" => "82"),
    array("name" => "Nepali - नेपाली", "code" => "ne", "native_name" => "नेपाली", "id" => "83"),
    array("name" => "Norwegian - norsk", "code" => "no", "native_name" => "norsk", "id" => "84"),
    array("name" => "Norwegian Bokmål - norsk bokmål", "code" => "nb", "native_name" => "norsk bokmål", "id" => "85"),
    array("name" => "Norwegian Nynorsk - nynorsk", "code" => "nn", "native_name" => "nynorsk", "id" => "86"),
    array("name" => "Occitan", "code" => "oc", "native_name" => "Occitan", "id" => "87"),
    array("name" => "Oriya - ଓଡ଼ିଆ", "code" => "or", "native_name" => "ଓଡ଼ିଆ", "id" => "88"),
    array("name" => "Oromo - Oromoo", "code" => "om", "native_name" => "Oromoo", "id" => "89"),
    array("name" => "Pashto - پښتو", "code" => "ps", "native_name" => "پښتو", "id" => "90"),
    array("name" => "Persian - فارسی", "code" => "fa", "native_name" => "فارسی", "id" => "91"),
    array("name" => "Polish - polski", "code" => "pl", "native_name" => "polski", "id" => "92"),
    array("name" => "Portuguese - português", "code" => "pt", "native_name" => "português", "id" => "93"),
    array("name" => "Portuguese (Brazil) - português (Brasil)", "code" => "pt-BR", "native_name" => "português (Brasil)", "id" => "94"),
    array("name" => "Portuguese (Portugal) - português (Portugal)", "code" => "pt-PT", "native_name" => "português (Portugal)", "id" => "95"),
    array("name" => "Punjabi - ਪੰਜਾਬੀ", "code" => "pa", "native_name" => "ਪੰਜਾਬੀ", "id" => "96"),
    array("name" => "Quechua", "code" => "qu", "native_name" => "Quechua", "id" => "97"),
    array("name" => "Romanian - română", "code" => "ro", "native_name" => "română", "id" => "98"),
    array("name" => "Romanian (Moldova) - română (Moldova)", "code" => "mo", "native_name" => "română (Moldova)", "id" => "99"),
    array("name" => "Romansh - rumantsch", "code" => "rm", "native_name" => "rumantsch", "id" => "100"),
    array("name" => "Russian - русский", "code" => "ru", "native_name" => "русский", "id" => "101"),
    array("name" => "Scottish Gaelic", "code" => "gd", "native_name" => "Scottish Gaelic", "id" => "102"),
    array("name" => "Serbian - српски", "code" => "sr", "native_name" => "српски", "id" => "103"),
    array("name" => "Serbo - Croatian", "code" => "sh", "native_name" => "Croatian", "id" => "104"),
    array("name" => "Shona - chiShona", "code" => "sn", "native_name" => "chiShona", "id" => "105"),
    array("name" => "Sindhi", "code" => "sd", "native_name" => "Sindhi", "id" => "106"),
    array("name" => "Sinhala - සිංහල", "code" => "si", "native_name" => "සිංහල", "id" => "107"),
    array("name" => "Slovak - slovenčina", "code" => "sk", "native_name" => "slovenčina", "id" => "108"),
    array("name" => "Slovenian - slovenščina", "code" => "sl", "native_name" => "slovenščina", "id" => "109"),
    array("name" => "Somali - Soomaali", "code" => "so", "native_name" => "Soomaali", "id" => "110"),
    array("name" => "Southern Sotho", "code" => "st", "native_name" => "Southern Sotho", "id" => "111"),
    array("name" => "Spanish - español", "code" => "es", "native_name" => "español", "id" => "112"),
    array("name" => "Spanish (Argentina) - español (Argentina)", "code" => "es-AR", "native_name" => "español (Argentina)", "id" => "113"),
    array("name" => "Spanish (Latin America) - español (Latinoamérica)", "code" => "es-419", "native_name" => "español (Latinoamérica)", "id" => "114"),
    array("name" => "Spanish (Mexico) - español (México)", "code" => "es-MX", "native_name" => "español (México)", "id" => "115"),
    array("name" => "Spanish (Spain) - español (España)", "code" => "es-ES", "native_name" => "español (España)", "id" => "116"),
    array("name" => "Spanish (United States) - español (Estados Unidos)", "code" => "es-US", "native_name" => "español (Estados Unidos)", "id" => "117"),
    array("name" => "Sundanese", "code" => "su", "native_name" => "Sundanese", "id" => "118"),
    array("name" => "Swahili - Kiswahili", "code" => "sw", "native_name" => "Kiswahili", "id" => "119"),
    array("name" => "Swedish - svenska", "code" => "sv", "native_name" => "svenska", "id" => "120"),
    array("name" => "Tajik - тоҷикӣ", "code" => "tg", "native_name" => "тоҷикӣ", "id" => "121"),
    array("name" => "Tamil - தமிழ்", "code" => "ta", "native_name" => "தமிழ்", "id" => "122"),
    array("name" => "Tatar", "code" => "tt", "native_name" => "Tatar", "id" => "123"),
    array("name" => "Telugu - తెలుగు", "code" => "te", "native_name" => "తెలుగు", "id" => "124"),
    array("name" => "Thai - ไทย", "code" => "th", "native_name" => "ไทย", "id" => "125"),
    array("name" => "Tigrinya - ትግርኛ", "code" => "ti", "native_name" => "ትግርኛ", "id" => "126"),
    array("name" => "Tongan - lea fakatonga", "code" => "to", "native_name" => "lea fakatonga", "id" => "127"),
    array("name" => "Turkish - Türkçe", "code" => "tr", "native_name" => "Türkçe", "id" => "128"),
    array("name" => "Turkmen", "code" => "tk", "native_name" => "Turkmen", "id" => "129"),
    array("name" => "Twi", "code" => "tw", "native_name" => "Twi", "id" => "130"),
    array("name" => "Ukrainian - українська", "code" => "uk", "native_name" => "українська", "id" => "131"),
    array("name" => "Urdu - اردو", "code" => "ur", "native_name" => "اردو", "id" => "132"),
    array("name" => "Uyghur", "code" => "ug", "native_name" => "Uyghur", "id" => "133"),
    array("name" => "Uzbek - o‘zbek", "code" => "uz", "native_name" => "o‘zbek", "id" => "134"),
    array("name" => "Vietnamese - Tiếng Việt", "code" => "vi", "native_name" => "Tiếng Việt", "id" => "135"),
    array("name" => "Walloon - wa", "code" => "wa", "native_name" => "wa", "id" => "136"),
    array("name" => "Welsh - Cymraeg", "code" => "cy", "native_name" => "Cymraeg", "id" => "137"),
    array("name" => "Western Frisian", "code" => "fy", "native_name" => "Western Frisian", "id" => "138"),
    array("name" => "Xhosa", "code" => "xh", "native_name" => "Xhosa", "id" => "139"),
    array("name" => "Yiddish", "code" => "yi", "native_name" => "Yiddish", "id" => "140"),
    array("name" => "Yoruba - Èdè Yorùbá", "code" => "yo", "native_name" => "Èdè Yorùbá", "id" => "141"),
    array("name" => "Zulu - isiZulu", "code" => "zu", "native_name" => "isiZulu", "id" => "142")
);

$languages_list_obiect = array(
    "af" => array("name" => "Afrikaans", "native_name" => "Afrikaans", "id" => "1"),
    "sq" => array("name" => "Albanian - shqip", "native_name" => "shqip", "id" => "2"),
    "am" => array("name" => "Amharic - አማርኛ", "native_name" => "አማርኛ", "id" => "3"),
    "ar" => array("name" => "Arabic - العربية", "native_name" => "العربية", "id" => "4"),
    "an" => array("name" => "Aragonese - aragonés", "native_name" => "aragonés", "id" => "5"),
    "hy" => array("name" => "Armenian - հայերեն", "native_name" => "հայերեն", "id" => "6"),
    "ast" => array("name" => "Asturian - asturianu", "native_name" => "asturianu", "id" => "7"),
    "az" => array("name" => "Azerbaijani - azərbaycan dili", "native_name" => "azərbaycan dili", "id" => "8"),
    "eu" => array("name" => "Basque - euskara", "native_name" => "euskara", "id" => "9"),
    "be" => array("name" => "Belarusian - беларуская", "native_name" => "беларуская", "id" => "10"),
    "bn" => array("name" => "Bengali - বাংলা", "native_name" => "বাংলা", "id" => "11"),
    "bs" => array("name" => "Bosnian - bosanski", "native_name" => "bosanski", "id" => "12"),
    "br" => array("name" => "Breton - brezhoneg", "native_name" => "brezhoneg", "id" => "13"),
    "bg" => array("name" => "Bulgarian - български", "native_name" => "български", "id" => "14"),
    "ca" => array("name" => "Catalan - català", "native_name" => "català", "id" => "15"),
    "ckb" => array("name" => "Central Kurdish - کوردی (دەستنوسی عەرەبی)", "native_name" => "کوردی (دەستنوسی عەرەبی)", "id" => "16"),
    "zh" => array("name" => "Chinese - 中文", "native_name" => "中文", "id" => "17"),
    "zh-HK" => array("name" => "Chinese (Hong Kong) - 中文（香港）", "native_name" => "中文（香港）", "id" => "18"),
    "zh-CN" => array("name" => "Chinese (Simplified) - 中文（简体）", "native_name" => "中文（简体）", "id" => "19"),
    "zh-TW" => array("name" => "Chinese (Traditional) - 中文（繁體）", "native_name" => "中文（繁體）", "id" => "20"),
    "co" => array("name" => "Corsican", "native_name" => "Corsican", "id" => "21"),
    "hr" => array("name" => "Croatian - hrvatski", "native_name" => "hrvatski", "id" => "22"),
    "cs" => array("name" => "Czech - čeština", "native_name" => "čeština", "id" => "23"),
    "da" => array("name" => "Danish - dansk", "native_name" => "dansk", "id" => "24"),
    "nl" => array("name" => "Dutch - Nederlands", "native_name" => "Nederlands", "id" => "25"),
    "en" => array("name" => "English", "native_name" => "English", "id" => "26"),
    "en-AU" => array("name" => "English (Australia)", "native_name" => "English (Australia)", "id" => "27"),
    "en-CA" => array("name" => "English (Canada)", "native_name" => "English (Canada)", "id" => "28"),
    "en-IN" => array("name" => "English (India)", "native_name" => "English (India)", "id" => "29"),
    "en-NZ" => array("name" => "English (New Zealand)", "native_name" => "English (New Zealand)", "id" => "30"),
    "en-ZA" => array("name" => "English (South Africa)", "native_name" => "English (South Africa)", "id" => "31"),
    "en-GB" => array("name" => "English (United Kingdom)", "native_name" => "English (United Kingdom)", "id" => "32"),
    "en-US" => array("name" => "English (United States)", "native_name" => "English (United States)", "id" => "33"),
    "eo" => array("name" => "Esperanto - esperanto", "native_name" => "esperanto", "id" => "34"),
    "et" => array("name" => "Estonian - eesti", "native_name" => "eesti", "id" => "35"),
    "fo" => array("name" => "Faroese - føroyskt", "native_name" => "føroyskt", "id" => "36"),
    "fil" => array("name" => "Filipino", "native_name" => "Filipino", "id" => "37"),
    "fi" => array("name" => "Finnish - suomi", "native_name" => "suomi", "id" => "38"),
    "fr" => array("name" => "French - français", "native_name" => "français", "id" => "39"),
    "fr-CA" => array("name" => "French (Canada) - français (Canada)", "native_name" => "français (Canada)", "id" => "40"),
    "fr-FR" => array("name" => "French (France) - français (France)", "native_name" => "français (France)", "id" => "41"),
    "fr-CH" => array("name" => "French (Switzerland) - français (Suisse)", "native_name" => "français (Suisse)", "id" => "42"),
    "gl" => array("name" => "Galician - galego", "native_name" => "galego", "id" => "43"),
    "ka" => array("name" => "Georgian - ქართული", "native_name" => "ქართული", "id" => "44"),
    "de" => array("name" => "German - Deutsch", "native_name" => "Deutsch", "id" => "45"),
    "de-AT" => array("name" => "German (Austria) - Deutsch (Österreich)", "native_name" => "Deutsch (Österreich)", "id" => "46"),
    "de-DE" => array("name" => "German (Germany) - Deutsch (Deutschland)", "native_name" => "Deutsch (Deutschland)", "id" => "47"),
    "de-LI" => array("name" => "German (Liechtenstein) - Deutsch (Liechtenstein)", "native_name" => "Deutsch (Liechtenstein)", "id" => "48"),
    "de-CH" => array("name" => "German (Switzerland) - Deutsch (Schweiz)", "native_name" => "Deutsch (Schweiz)", "id" => "49"),
    "el" => array("name" => "Greek - Ελληνικά", "native_name" => "Ελληνικά", "id" => "50"),
    "gn" => array("name" => "Guarani", "native_name" => "Guarani", "id" => "51"),
    "gu" => array("name" => "Gujarati - ગુજરાતી", "native_name" => "ગુજરાતી", "id" => "52"),
    "ha" => array("name" => "Hausa", "native_name" => "Hausa", "id" => "53"),
    "haw" => array("name" => "Hawaiian - ʻŌlelo Hawaiʻi", "native_name" => "ʻŌlelo Hawaiʻi", "id" => "54"),
    "he" => array("name" => "Hebrew - עברית", "native_name" => "עברית", "id" => "55"),
    "hi" => array("name" => "Hindi - हिन्दी", "native_name" => "हिन्दी", "id" => "56"),
    "hu" => array("name" => "Hungarian - magyar", "native_name" => "magyar", "id" => "57"),
    "is" => array("name" => "Icelandic - íslenska", "native_name" => "íslenska", "id" => "58"),
    "id" => array("name" => "Indonesian - Indonesia", "native_name" => "Indonesia", "id" => "59"),
    "ia" => array("name" => "Interlingua", "native_name" => "Interlingua", "id" => "60"),
    "ga" => array("name" => "Irish - Gaeilge", "native_name" => "Gaeilge", "id" => "61"),
    "it" => array("name" => "Italian - italiano", "native_name" => "italiano", "id" => "62"),
    "it-IT" => array("name" => "Italian (Italy) - italiano (Italia)", "native_name" => "italiano (Italia)", "id" => "63"),
    "it-CH" => array("name" => "Italian (Switzerland) - italiano (Svizzera)", "native_name" => "italiano (Svizzera)", "id" => "64"),
    "ja" => array("name" => "Japanese - 日本語", "native_name" => "日本語", "id" => "65"),
    "kn" => array("name" => "Kannada - ಕನ್ನಡ", "native_name" => "ಕನ್ನಡ", "id" => "66"),
    "kk" => array("name" => "Kazakh - қазақ тілі", "native_name" => "қазақ тілі", "id" => "67"),
    "km" => array("name" => "Khmer - ខ្មែរ", "native_name" => "ខ្មែរ", "id" => "68"),
    "ko" => array("name" => "Korean - 한국어", "native_name" => "한국어", "id" => "69"),
    "ku" => array("name" => "Kurdish - Kurdî", "native_name" => "Kurdî", "id" => "70"),
    "ky" => array("name" => "Kyrgyz - кыргызча", "native_name" => "кыргызча", "id" => "71"),
    "lo" => array("name" => "Lao - ລາວ", "native_name" => "ລາວ", "id" => "72"),
    "la" => array("name" => "Latin", "native_name" => "Latin", "id" => "73"),
    "lv" => array("name" => "Latvian - latviešu", "native_name" => "latviešu", "id" => "74"),
    "ln" => array("name" => "Lingala - lingála", "native_name" => "lingála", "id" => "75"),
    "lt" => array("name" => "Lithuanian - lietuvių", "native_name" => "lietuvių", "id" => "76"),
    "mk" => array("name" => "Macedonian - македонски", "native_name" => "македонски", "id" => "77"),
    "ms" => array("name" => "Malay - Bahasa Melayu", "native_name" => "Bahasa Melayu", "id" => "78"),
    "ml" => array("name" => "Malayalam - മലയാളം", "native_name" => "മലയാളം", "id" => "79"),
    "mt" => array("name" => "Maltese - Malti", "native_name" => "Malti", "id" => "80"),
    "mr" => array("name" => "Marathi - मराठी", "native_name" => "मराठी", "id" => "81"),
    "mn" => array("name" => "Mongolian - монгол", "native_name" => "монгол", "id" => "82"),
    "ne" => array("name" => "Nepali - नेपाली", "native_name" => "नेपाली", "id" => "83"),
    "no" => array("name" => "Norwegian - norsk", "native_name" => "norsk", "id" => "84"),
    "nb" => array("name" => "Norwegian Bokmål - norsk bokmål", "native_name" => "norsk bokmål", "id" => "85"),
    "nn" => array("name" => "Norwegian Nynorsk - nynorsk", "native_name" => "nynorsk", "id" => "86"),
    "oc" => array("name" => "Occitan", "native_name" => "Occitan", "id" => "87"),
    "or" => array("name" => "Oriya - ଓଡ଼ିଆ", "native_name" => "ଓଡ଼ିଆ", "id" => "88"),
    "om" => array("name" => "Oromo - Oromoo", "native_name" => "Oromoo", "id" => "89"),
    "ps" => array("name" => "Pashto - پښتو", "native_name" => "پښتو", "id" => "90"),
    "fa" => array("name" => "Persian - فارسی", "native_name" => "فارسی", "id" => "91"),
    "pl" => array("name" => "Polish - polski", "native_name" => "polski", "id" => "92"),
    "pt" => array("name" => "Portuguese - português", "native_name" => "português", "id" => "93"),
    "pt-BR" => array("name" => "Portuguese (Brazil) - português (Brasil)", "native_name" => "português (Brasil)", "id" => "94"),
    "pt-PT" => array("name" => "Portuguese (Portugal) - português (Portugal)", "native_name" => "português (Portugal)", "id" => "95"),
    "pa" => array("name" => "Punjabi - ਪੰਜਾਬੀ", "native_name" => "ਪੰਜਾਬੀ", "id" => "96"),
    "qu" => array("name" => "Quechua", "native_name" => "Quechua", "id" => "97"),
    "ro" => array("name" => "Romanian - română", "native_name" => "română", "id" => "98"),
    "mo" => array("name" => "Romanian (Moldova) - română (Moldova)", "native_name" => "română (Moldova)", "id" => "99"),
    "rm" => array("name" => "Romansh - rumantsch", "native_name" => "rumantsch", "id" => "100"),
    "ru" => array("name" => "Russian - русский", "native_name" => "русский", "id" => "101"),
    "gd" => array("name" => "Scottish Gaelic", "native_name" => "Scottish Gaelic", "id" => "102"),
    "sr" => array("name" => "Serbian - српски", "native_name" => "српски", "id" => "103"),
    "sh" => array("name" => "Serbo - Croatian", "native_name" => "Croatian", "id" => "104"),
    "sn" => array("name" => "Shona - chiShona", "native_name" => "chiShona", "id" => "105"),
    "sd" => array("name" => "Sindhi", "native_name" => "Sindhi", "id" => "106"),
    "si" => array("name" => "Sinhala - සිංහල", "native_name" => "සිංහල", "id" => "107"),
    "sk" => array("name" => "Slovak - slovenčina", "native_name" => "slovenčina", "id" => "108"),
    "sl" => array("name" => "Slovenian - slovenščina", "native_name" => "slovenščina", "id" => "109"),
    "so" => array("name" => "Somali - Soomaali", "native_name" => "Soomaali", "id" => "110"),
    "st" => array("name" => "Southern Sotho", "native_name" => "Southern Sotho", "id" => "111"),
    "es" => array("name" => "Spanish - español", "native_name" => "español", "id" => "112"),
    "es-AR" => array("name" => "Spanish (Argentina) - español (Argentina)", "native_name" => "español (Argentina)", "id" => "113"),
    "es-419" => array("name" => "Spanish (Latin America) - español (Latinoamérica)", "native_name" => "español (Latinoamérica)", "id" => "114"),
    "es-MX" => array("name" => "Spanish (Mexico) - español (México)", "native_name" => "español (México)", "id" => "115"),
    "es-ES" => array("name" => "Spanish (Spain) - español (España)", "native_name" => "español (España)", "id" => "116"),
    "es-US" => array("name" => "Spanish (United States) - español (Estados Unidos)", "native_name" => "español (Estados Unidos)", "id" => "117"),
    "su" => array("name" => "Sundanese", "native_name" => "Sundanese", "id" => "118"),
    "sw" => array("name" => "Swahili - Kiswahili", "native_name" => "Kiswahili", "id" => "119"),
    "sv" => array("name" => "Swedish - svenska", "native_name" => "svenska", "id" => "120"),
    "tg" => array("name" => "Tajik - тоҷикӣ", "native_name" => "тоҷикӣ", "id" => "121"),
    "ta" => array("name" => "Tamil - தமிழ்", "native_name" => "தமிழ்", "id" => "122"),
    "tt" => array("name" => "Tatar", "native_name" => "Tatar", "id" => "123"),
    "te" => array("name" => "Telugu - తెలుగు", "native_name" => "తెలుగు", "id" => "124"),
    "th" => array("name" => "Thai - ไทย", "native_name" => "ไทย", "id" => "125"),
    "ti" => array("name" => "Tigrinya - ትግርኛ", "native_name" => "ትግርኛ", "id" => "126"),
    "to" => array("name" => "Tongan - lea fakatonga", "native_name" => "lea fakatonga", "id" => "127"),
    "tr" => array("name" => "Turkish - Türkçe", "native_name" => "Türkçe", "id" => "128"),
    "tk" => array("name" => "Turkmen", "native_name" => "Turkmen", "id" => "129"),
    "tw" => array("name" => "Twi", "native_name" => "Twi", "id" => "130"),
    "uk" => array("name" => "Ukrainian - українська", "native_name" => "українська", "id" => "131"),
    "ur" => array("name" => "Urdu - اردو", "native_name" => "اردو", "id" => "132"),
    "ug" => array("name" => "Uyghur", "native_name" => "Uyghur", "id" => "133"),
    "uz" => array("name" => "Uzbek - o‘zbek", "native_name" => "o‘zbek", "id" => "134"),
    "vi" => array("name" => "Vietnamese - Tiếng Việt", "native_name" => "Tiếng Việt", "id" => "135"),
    "wa" => array("name" => "Walloon - wa", "native_name" => "wa", "id" => "136"),
    "cy" => array("name" => "Welsh - Cymraeg", "native_name" => "Cymraeg", "id" => "137"),
    "fy" => array("name" => "Western Frisian", "native_name" => "Western Frisian", "id" => "138"),
    "xh" => array("name" => "Xhosa", "native_name" => "Xhosa", "id" => "139"),
    "yi" => array("name" => "Yiddish", "native_name" => "Yiddish", "id" => "140"),
    "yo" => array("name" => "Yoruba - Èdè Yorùbá", "native_name" => "Èdè Yorùbá", "id" => "141"),
    "zu" => array("name" => "Zulu - isiZulu", "native_name" => "isiZulu", "id" => "142")
);

?>